config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#index"
  
  get  "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create" 
  delete "/signout", to: "sessions#destroy"
  
  resources :users
  resources :meetings
  
  namespace :api, defaults: {format: 'json'}  do
    namespace :v1 do
      resources :conversations
    end
  end
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def index
    @meetings = Meeting.all
  end
  
  def show
    
  end
  
  def new
    @meeting = Meeting.new
  end
  
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.master_user_id = @current_user.id
    if @meeting.save
      flash[:notice] = I18n.t('controller.meetings.created')
      redirect_to :action => "index"
    else
      flash[:alert] = I18n.t('controller.meetings.not_created')
      render "new"
    end
  end
  
  private
  
  def meeting_params
    params.require(:meeting).permit(:name, :description)
  end
end

app/views/meetings/index.html.erb
<div class="content">
	<div class="panel panel-default hdr-spacer">
		<div class="panel-heading">
			<h3 class="panel-title">Groups</h3>
		</div>
		<div class="panel-body">
			<div class="hdr-bottom-spacer pull-right">
				<%= button_to "New Meeting", new_meeting_path, method: :get, class: 'btn btn-primary'  %>
			</div>
			<div class="row">
				<div class="col-md-12">
					<table class="table table-condensed table-hover table-striped dataTable">
						<thead>
							<tr>
								<th>ID</th>
								<th>Name</th>
								<th>Description</th>
								<th>Status</th>
							</tr>
						</thead>
						<tbody>
							<% @meetings.each do |meeting| %>
							<tr>
								<td><%= link_to meeting.id, meeting_path(meeting.id, data: { no_turbolink: true } ) %></td>
								<td><%= meeting.name %></td>
								<td><%= meeting.description %></td>
								<td><%= meeting.status %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/meetings/new.html.erb
<div class="content">
	<div class="panel panel-default hdr-spacer">
		<div class="panel-heading">
			<h3 class="panel-title">New Meeting</h3>
		</div>
		<div class="panel-body">
			<%= bootstrap_form_for(@meeting) do |f| %>
			<div class="row">
				<div class="col-md-12">
					<%= f.text_field :name %>
					<%= f.text_field :description %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<%= f.submit class: 'btn btn-success' %>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/meetings/show.html.erb
<div class="content">
	TODO Create Meeting System
</div>